/// The authoritative query-normalization pipeline for vocabulary search.
///
/// This is a direct implementation of
/// `wellapath-knowledge-base docs/VOCABULARY_NORMALIZATION_SPEC.md`
/// (normalization version 1.0.0), vendored at
/// `test/fixtures/vocabulary/docs/VOCABULARY_NORMALIZATION_SPEC.md`.
///
/// Mobile and Backend must reproduce this function exactly. Where this file and
/// that document disagree, one of them is defective — it is not licence to
/// diverge. Conformance is pinned by every case in
/// `search_cases_v1.json`.
///
/// ## What this deliberately does NOT do
///
/// Every omission below is a safety property. Matching is **whole-string
/// equality only**, so none of these can be reintroduced by the resolver
/// either:
///
/// - no stemming or lemmatization — `fevers` must not become `fever`
/// - no plural folding
/// - no spelling correction — `fver` must not become `fever`
/// - no edit-distance or fuzzy matching, anywhere
/// - no substring or prefix matching — `feve` must not match `fever`
/// - no stopword removal — dropping `no`/`not`/`without` would erase negation
/// - no synonym expansion — synonyms are authored, reviewed aliases
/// - no diacritic stripping — deferred, and would require a version bump
/// - no semantic similarity, no AI/LLM matching, no server round-trip
///
/// The combination of "negation words survive" and "whole-string equality"
/// is what makes `no fever` resolve to nothing rather than to `fever`. That is
/// the single most important behaviour in this file.
library;

import 'package:unorm_dart/unorm_dart.dart' as unorm;

/// The normalization contract version this file implements.
///
/// Checked against the artifact's `search_index.normalization_version`: an
/// artifact generated by a different pipeline must not be silently searched
/// with this one.
const String kNormalizationVersion = '1.0.0';

/// Codepoints folded to ASCII `'` before and after NFKC.
const Set<int> _apostropheLike = <int>{
  0x2018,
  0x2019,
  0x201B,
  0x02B9,
  0x02BB,
  0x02BC,
  0x00B4,
  0x0060,
};

/// Codepoints folded to ASCII `-`. Covers U+2010–U+2015 plus the minus sign
/// and the two small/fullwidth forms.
bool _isDashLike(int c) =>
    (c >= 0x2010 && c <= 0x2015) || c == 0x2212 || c == 0xFE58 || c == 0xFE63;

/// Codepoints folded to ASCII space. Covers U+2000–U+200A plus the isolated
/// space-like characters, the zero-width space and the BOM.
bool _isSpaceLike(int c) =>
    c == 0x00A0 ||
    c == 0x1680 ||
    (c >= 0x2000 && c <= 0x200A) ||
    c == 0x200B ||
    c == 0x202F ||
    c == 0x205F ||
    c == 0x3000 ||
    c == 0xFEFF;

bool _isAsciiDigit(int c) => c >= 0x30 && c <= 0x39;

/// Step 1 — variant folding.
///
/// Run on **both sides of NFKC**. Some of these characters are decomposed by
/// NFKC into forms this map would no longer recognise (U+00B4 ACUTE ACCENT
/// becomes SPACE + U+0301 COMBINING ACUTE ACCENT), so a fold applied only
/// afterwards silently misses them. The map is idempotent on its own output,
/// so running it twice is safe.
String _foldVariants(String value) {
  final StringBuffer out = StringBuffer();
  for (final int c in value.runes) {
    if (_apostropheLike.contains(c)) {
      out.writeCharCode(0x27); // '
    } else if (_isDashLike(c)) {
      out.writeCharCode(0x2D); // -
    } else if (_isSpaceLike(c)) {
      out.writeCharCode(0x20); // space
    } else {
      out.writeCharCode(c);
    }
  }
  return out.toString();
}

/// True for a letter or digit in any script.
///
/// Dart's `RegExp` with `unicode: true` gives us the Unicode property escapes
/// the spec's "letter or digit (any script)" rule needs; a manual ASCII range
/// check would silently drop non-Latin input.
final RegExp _letterOrDigit = RegExp(r'[\p{L}\p{N}]', unicode: true);

bool _isLetterOrDigit(String ch) => _letterOrDigit.hasMatch(ch);

/// Step 5 — the punctuation pass, character by character.
///
/// | Character                         | Rule                                |
/// |-----------------------------------|-------------------------------------|
/// | letter or digit (any script)      | kept                                |
/// | `.` directly between ASCII digits | kept — decimal point, `38.5`        |
/// | `/` directly between ASCII digits | kept — ratio, `140/90`              |
/// | `,` directly between ASCII digits | deleted — thousands sep, `1,000`    |
/// | anything else                     | replaced by a single space          |
///
/// `-` falls into the last row deliberately: hyphens become **spaces, not
/// nothing**. Deleting them would turn `chest-pain` into `chestpain`, which
/// matches no token.
String _punctuationPass(String value) {
  final List<int> codes = value.runes.toList();
  final StringBuffer out = StringBuffer();

  for (int i = 0; i < codes.length; i++) {
    final int c = codes[i];
    final String ch = String.fromCharCode(c);

    if (_isLetterOrDigit(ch)) {
      out.write(ch);
      continue;
    }

    final bool betweenDigits =
        i > 0 &&
        i < codes.length - 1 &&
        _isAsciiDigit(codes[i - 1]) &&
        _isAsciiDigit(codes[i + 1]);

    if (betweenDigits && (c == 0x2E || c == 0x2F)) {
      out.write(ch); // decimal point or ratio solidus
      continue;
    }
    if (betweenDigits && c == 0x2C) {
      continue; // thousands separator — deleted, not spaced
    }

    out.write(' ');
  }

  return out.toString();
}

final RegExp _whitespaceRun = RegExp(r'\s+');

/// Normalizes [value] per the authoritative pipeline.
///
/// Pure, total, idempotent and deterministic: the output depends only on the
/// input string — no locale, clock, randomness, dictionary or network. Every
/// string input yields a string output; it never throws on content.
String normalizeVocabularyQuery(String value) {
  // Step 1 — variant folding, pre-NFKC.
  String s = _foldVariants(value);

  // Step 2 — Unicode NFKC. Folds fullwidth forms, compatibility ligatures and
  // most exotic spaces.
  s = unorm.nfkc(s);

  // Step 1 again — post-NFKC, for the characters NFKC decomposed.
  s = _foldVariants(s);

  // Step 3 — full Unicode case folding. Not ASCII-only.
  s = s.toLowerCase();

  // Step 4 — ASCII apostrophe deleted with no replacement, so `Ludwig's
  // angina` and `Ludwig’s angina` both give `ludwigs angina`.
  s = s.replaceAll("'", '');

  // Step 5 — punctuation pass.
  s = _punctuationPass(s);

  // Step 6 — collapse whitespace runs to one ASCII space, then trim.
  s = s.replaceAll(_whitespaceRun, ' ').trim();

  return s;
}

/// `normalize_token_id(id) = normalize(id.replace("_", " "))`.
///
/// The underscore is the word separator in `lowercase_snake_case`, so it
/// becomes a space *before* the standard pipeline runs: `chest_pain` →
/// `chest pain`. This is the value the artifact stores in
/// `tokens[].search.normalized_form`.
String normalizeTokenId(String tokenId) =>
    normalizeVocabularyQuery(tokenId.replaceAll('_', ' '));
