/// Deterministic Dart mirror of backend telemetry contract v1.0.
///
/// **Source of truth:** `wellapath-backend` `docs/contracts/telemetry.v1.allowlist.json`
/// at merge commit `5e13379f19c53ec90cee7958dc029d908c342dcd` (PR #29).
///
/// This file is hand-written rather than generated: the backend generator emits
/// TypeScript and JSON only, and adding a TS→Dart codegen step to this repo was
/// not in scope for I1. The safety property that codegen would have given us is
/// instead enforced by `test/telemetry/contract_parity_test.dart`, which loads
/// the vendored `telemetry.v1.allowlist.json` and asserts this mirror matches it
/// field for field, in both directions. **If the backend ships a new contract,
/// that test fails in CI** — which is the point. Do not edit this file to make
/// the test pass; re-vendor the artifact and mirror the change deliberately.
///
/// Nothing here may be widened to admit a field the backend does not declare.
/// The allowlist is the primary privacy control; see `privacy_guard.dart` for
/// the second defensive layer that runs behind it.
library;

/// The wire types the contract uses. There is deliberately no `object` or
/// `array` member — the contract accepts scalars only, and a nested value is a
/// rejection (`nested_value_not_allowed`), not a shape to be serialised.
enum TelemetryFieldType { string, integer, boolean, enumeration }

/// One allowlisted field and every constraint the backend will enforce on it.
class TelemetryFieldSpec {
  const TelemetryFieldSpec({
    required this.field,
    required this.type,
    required this.required,
    this.allowedValues,
    this.maxLength,
    this.pattern,
    this.minimum,
    this.maximum,
  });

  final String field;
  final TelemetryFieldType type;
  final bool required;

  /// Populated for [TelemetryFieldType.enumeration] only.
  final List<String>? allowedValues;

  final int? maxLength;

  /// Unanchored, exactly as the allowlist artifact carries it. Callers must
  /// anchor it themselves — see [anchoredPattern].
  final String? pattern;

  final int? minimum;
  final int? maximum;

  /// [pattern] anchored to the whole value.
  ///
  /// The allowlist stores patterns unanchored while the JSON Schema stores the
  /// same expressions wrapped as `^(?:…)$`. An unanchored match would accept
  /// `lat=6.52,lon=3.37` for a field whose pattern is `[A-Za-z0-9_.:-]{1,64}`,
  /// so anchoring is a privacy control, not a formatting detail.
  RegExp? get anchoredPattern =>
      pattern == null ? null : RegExp('^(?:$pattern)\$');
}

/// One allowlisted event and the properties it may carry, beyond the three
/// common fields every event carries.
class TelemetryEventSpec {
  const TelemetryEventSpec({required this.eventName, required this.properties});

  final String eventName;
  final List<TelemetryFieldSpec> properties;

  TelemetryFieldSpec? property(String field) {
    for (final spec in properties) {
      if (spec.field == field) return spec;
    }
    return null;
  }
}

/// Contract v1.0, mirrored.
abstract final class TelemetryContract {
  const TelemetryContract._();

  /// Sent as `contract_version` on every request. Never negotiated downward.
  static const String version = '1.0';

  /// The path appended to the configured telemetry base URL. The full endpoint
  /// is never hard-coded into application logic — see `TelemetryConfig`.
  static const String endpointPath = '/v1/telemetry/events';

  // ── Limits ────────────────────────────────────────────────────────────────

  static const int maxBodyBytes = 32768;
  static const int maxEventsPerBatch = 20;
  static const int minEventsPerBatch = 1;
  static const int maxClientTimestampAgeMs = 2592000000; // 30 days
  static const int maxClientTimestampSkewMs = 86400000; // 24 hours

  /// Local offline-queue ceiling. This is a client-side cap from the brief and
  /// §5 of the contract doc ("500 events is the recommended ceiling"), not a
  /// server-enforced limit, so it is not part of the parity check.
  static const int maxQueuedEvents = 500;

  /// Per-request timeout. Contract §5.
  static const Duration requestTimeout = Duration(seconds: 10);

  /// At most 3 attempts per batch. Contract §5.
  static const int maxAttemptsPerBatch = 3;

  /// Backoff base delays, indexed by completed-attempt count. With
  /// [maxAttemptsPerBatch] of 3 only the first two are ever used (2 s, then
  /// 4 s); the 8 s entry is carried because the contract documents the
  /// sequence as `2 s, 4 s, 8 s` and a future attempt-count change should not
  /// silently fall off the end of the list.
  static const List<Duration> backoff = [
    Duration(seconds: 2),
    Duration(seconds: 4),
    Duration(seconds: 8),
  ];

  // ── Envelope ──────────────────────────────────────────────────────────────

  static const String tsPattern =
      r'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,3})?Z';

  static const List<TelemetryFieldSpec> envelope = [
    TelemetryFieldSpec(
      field: 'contract_version',
      type: TelemetryFieldType.enumeration,
      required: true,
      allowedValues: ['1.0'],
    ),
    TelemetryFieldSpec(
      field: 'sent_at',
      type: TelemetryFieldType.string,
      required: true,
      maxLength: 24,
      pattern: tsPattern,
    ),
  ];

  static const List<TelemetryFieldSpec> appContext = [
    TelemetryFieldSpec(
      field: 'platform',
      type: TelemetryFieldType.enumeration,
      required: true,
      allowedValues: ['ios', 'android'],
    ),
    TelemetryFieldSpec(
      field: 'app_version',
      type: TelemetryFieldType.string,
      required: true,
      maxLength: 24,
      pattern: r'\d{1,3}\.\d{1,3}\.\d{1,3}(-[A-Za-z0-9.]{1,16})?',
    ),
    TelemetryFieldSpec(
      field: 'app_build',
      type: TelemetryFieldType.string,
      required: true,
      maxLength: 10,
      pattern: r'\d{1,10}',
    ),
    TelemetryFieldSpec(
      field: 'os_version',
      type: TelemetryFieldType.string,
      required: false,
      maxLength: 8,
      pattern: r'\d{1,3}(\.\d{1,3})?',
    ),
  ];

  static const List<TelemetryFieldSpec> commonEventFields = [
    TelemetryFieldSpec(
      field: 'event_name',
      type: TelemetryFieldType.enumeration,
      required: true,
      allowedValues: eventNames,
    ),
    TelemetryFieldSpec(
      field: 'event_id',
      type: TelemetryFieldType.string,
      required: true,
      maxLength: 64,
      pattern: r'[A-Za-z0-9_-]{8,64}',
    ),
    TelemetryFieldSpec(
      field: 'client_ts',
      type: TelemetryFieldType.string,
      required: true,
      maxLength: 24,
      pattern: tsPattern,
    ),
  ];

  // ── Events ────────────────────────────────────────────────────────────────

  static const List<String> eventNames = [
    'app_open',
    'assessment_start',
    'assessment_step_view',
    'assessment_complete',
    'result_view',
    'facility_search',
    'facility_view',
    'facility_call',
    'directions_open',
    'emergency_action',
    'library_article_view',
    'feedback_submit',
  ];

  /// The opaque per-assessment correlation ID. Not accepted on
  /// `emergency_action`, `facility_*`, `directions_open`,
  /// `library_article_view` or `feedback_submit` — see the contract's privacy
  /// notes for why each exclusion exists.
  static const TelemetryFieldSpec _sessionId = TelemetryFieldSpec(
    field: 'assessment_session_id',
    type: TelemetryFieldType.string,
    required: true,
    maxLength: 64,
    pattern: r'[A-Za-z0-9_-]{16,64}',
  );

  static const String _versionPattern = r'\d{1,3}(\.\d{1,3}){0,2}';
  static const String _contentIdPattern = r'[A-Za-z0-9_.:-]{1,64}';

  static const Map<String, TelemetryEventSpec> events = {
    'app_open': TelemetryEventSpec(
      eventName: 'app_open',
      properties: [
        TelemetryFieldSpec(
          field: 'launch_type',
          type: TelemetryFieldType.enumeration,
          required: true,
          allowedValues: ['cold', 'warm'],
        ),
        TelemetryFieldSpec(
          field: 'is_first_launch',
          type: TelemetryFieldType.boolean,
          required: false,
        ),
      ],
    ),
    'assessment_start': TelemetryEventSpec(
      eventName: 'assessment_start',
      properties: [
        _sessionId,
        TelemetryFieldSpec(
          field: 'flow_version',
          type: TelemetryFieldType.string,
          required: false,
          maxLength: 12,
          pattern: _versionPattern,
        ),
        TelemetryFieldSpec(
          field: 'entry_point',
          type: TelemetryFieldType.enumeration,
          required: false,
          allowedValues: ['home', 'library', 'facility_locator', 'deep_link'],
        ),
      ],
    ),
    'assessment_step_view': TelemetryEventSpec(
      eventName: 'assessment_step_view',
      properties: [
        _sessionId,
        TelemetryFieldSpec(
          field: 'step_index',
          type: TelemetryFieldType.integer,
          required: true,
          minimum: 0,
          maximum: 200,
        ),
        TelemetryFieldSpec(
          field: 'step_count',
          type: TelemetryFieldType.integer,
          required: false,
          minimum: 1,
          maximum: 200,
        ),
      ],
    ),
    'assessment_complete': TelemetryEventSpec(
      eventName: 'assessment_complete',
      properties: [
        _sessionId,
        TelemetryFieldSpec(
          field: 'completion_status',
          type: TelemetryFieldType.enumeration,
          required: true,
          allowedValues: ['completed', 'abandoned', 'interrupted'],
        ),
        TelemetryFieldSpec(
          field: 'duration_ms',
          type: TelemetryFieldType.integer,
          required: false,
          minimum: 0,
          maximum: 7200000,
        ),
        TelemetryFieldSpec(
          field: 'step_count',
          type: TelemetryFieldType.integer,
          required: false,
          minimum: 0,
          maximum: 200,
        ),
      ],
    ),
    'result_view': TelemetryEventSpec(
      eventName: 'result_view',
      properties: [
        _sessionId,
        TelemetryFieldSpec(
          field: 'presentation_contract_version',
          type: TelemetryFieldType.string,
          required: false,
          maxLength: 12,
          pattern: _versionPattern,
        ),
      ],
    ),
    'facility_search': TelemetryEventSpec(
      eventName: 'facility_search',
      properties: [
        TelemetryFieldSpec(
          field: 'search_mode',
          type: TelemetryFieldType.enumeration,
          required: true,
          allowedValues: ['nearby', 'manual_area', 'name'],
        ),
        TelemetryFieldSpec(
          field: 'admin_area_code',
          type: TelemetryFieldType.enumeration,
          required: false,
          allowedValues: adminAreaCodes,
        ),
        TelemetryFieldSpec(
          field: 'result_count',
          type: TelemetryFieldType.integer,
          required: false,
          minimum: 0,
          maximum: 500,
        ),
      ],
    ),
    'facility_view': TelemetryEventSpec(
      eventName: 'facility_view',
      properties: [
        TelemetryFieldSpec(
          field: 'facility_id',
          type: TelemetryFieldType.string,
          required: true,
          maxLength: 64,
          pattern: _contentIdPattern,
        ),
        TelemetryFieldSpec(
          field: 'source',
          type: TelemetryFieldType.enumeration,
          required: false,
          allowedValues: ['search_results', 'map', 'saved', 'emergency_screen'],
        ),
      ],
    ),
    'facility_call': TelemetryEventSpec(
      eventName: 'facility_call',
      properties: [
        TelemetryFieldSpec(
          field: 'facility_id',
          type: TelemetryFieldType.string,
          required: true,
          maxLength: 64,
          pattern: _contentIdPattern,
        ),
        TelemetryFieldSpec(
          field: 'source',
          type: TelemetryFieldType.enumeration,
          required: false,
          allowedValues: [
            'search_results',
            'facility_detail',
            'emergency_screen',
          ],
        ),
      ],
    ),
    'directions_open': TelemetryEventSpec(
      eventName: 'directions_open',
      properties: [
        TelemetryFieldSpec(
          field: 'facility_id',
          type: TelemetryFieldType.string,
          required: true,
          maxLength: 64,
          pattern: _contentIdPattern,
        ),
        TelemetryFieldSpec(
          field: 'source',
          type: TelemetryFieldType.enumeration,
          required: false,
          allowedValues: [
            'search_results',
            'facility_detail',
            'emergency_screen',
          ],
        ),
      ],
    ),
    'emergency_action': TelemetryEventSpec(
      eventName: 'emergency_action',
      properties: [
        TelemetryFieldSpec(
          field: 'action_type',
          type: TelemetryFieldType.enumeration,
          required: true,
          allowedValues: [
            'call_emergency_number',
            'view_emergency_guidance',
            'dismiss_emergency_banner',
            'open_nearest_facility',
          ],
        ),
      ],
    ),
    'library_article_view': TelemetryEventSpec(
      eventName: 'library_article_view',
      properties: [
        TelemetryFieldSpec(
          field: 'article_id',
          type: TelemetryFieldType.string,
          required: true,
          maxLength: 64,
          pattern: _contentIdPattern,
        ),
        TelemetryFieldSpec(
          field: 'content_version',
          type: TelemetryFieldType.string,
          required: false,
          maxLength: 12,
          pattern: _versionPattern,
        ),
      ],
    ),
    'feedback_submit': TelemetryEventSpec(
      eventName: 'feedback_submit',
      properties: [
        TelemetryFieldSpec(
          field: 'rating',
          type: TelemetryFieldType.integer,
          required: true,
          minimum: 1,
          maximum: 5,
        ),
        TelemetryFieldSpec(
          field: 'category',
          type: TelemetryFieldType.enumeration,
          required: false,
          allowedValues: ['usability', 'performance', 'content', 'other'],
        ),
      ],
    ),
  };

  /// ISO 3166-2:NG state codes. Mirrored for completeness and for the parity
  /// test; **this client never populates `admin_area_code`**. The contract's §8
  /// records the artifact→code mapping as unconfirmed by the facilities owner,
  /// and the field is optional, so sending nothing is the correct behaviour. A
  /// wrong-but-valid code is worse than no code.
  static const List<String> adminAreaCodes = [
    'NG-AB', 'NG-AD', 'NG-AK', 'NG-AN', 'NG-BA', 'NG-BE', 'NG-BO', 'NG-BY', //
    'NG-CR', 'NG-DE', 'NG-EB', 'NG-ED', 'NG-EK', 'NG-EN', 'NG-FC', 'NG-GO',
    'NG-IM', 'NG-JI', 'NG-KD', 'NG-KE', 'NG-KN', 'NG-KO', 'NG-KT', 'NG-KW',
    'NG-LA', 'NG-NA', 'NG-NI', 'NG-OG', 'NG-ON', 'NG-OS', 'NG-OY', 'NG-PL',
    'NG-RI', 'NG-SO', 'NG-TA', 'NG-YO', 'NG-ZA',
  ];

  /// Fixed rejection codes the server may return, mirrored so diagnostics can
  /// classify a per-event rejection without inventing its own vocabulary.
  static const List<String> rejectionReasonCodes = [
    'malformed_json',
    'payload_too_large',
    'unsupported_content_type',
    'invalid_envelope',
    'unsupported_contract_version',
    'empty_batch',
    'batch_too_large',
    'telemetry_disabled',
    'rate_limited',
    'unknown_event',
    'unknown_property',
    'missing_required_property',
    'invalid_type',
    'invalid_enum_value',
    'invalid_format',
    'value_too_long',
    'value_out_of_range',
    'timestamp_out_of_range',
    'nested_value_not_allowed',
    'prohibited_field',
    'prohibited_container',
    'prohibited_value_shape',
    'unsafe_key',
    'payload_too_complex',
  ];
}
