const Map<String, String> kSymptomDisplayMap = {
  'Headache': 'headache',
  'Fever': 'fever',
  'Chills': 'chills',
  'Body pain': 'body_pain',
  'Weakness': 'weakness',
  'Nausea': 'nausea',
  'Sweating': 'sweating',
  'Cough': 'cough',
  'Fast breathing': 'fast_breathing_child',
  'Watery stool': 'watery_stool',
  'Vomiting': 'vomiting',
  'Abdominal cramps': 'abdominal_cramps',
  'Dizziness': 'dizziness',
  'Fatigue': 'fatigue',
  'Wrist pain': 'pain',
  'Swollen hands': 'swelling',
  'Dark urine': 'dark_urine',
  'Feeling sick or queasy': 'nausea',
  'Muscle pain': 'body_pain',
};
